export const WILAYAS = [
  "Adrar",
  "Aflou",
  "Aïn Defla",
  "Aïn Oussera",
  "Aïn Témouchent",
  "Algiers",
  "Annaba",
  "Barika",
  "Batna",
  "Béchar",
  "Béjaïa",
  "Bir El Ater",
  "Biskra",
  "Blida",
  "Bordj Bou Arréridj",
  "Bordj Baji Mokhtar",
  "Bou Saâda",
  "Bouira",
  "Boumerdès",
  "Béni Abbès",
  "Chlef",
  "Constantine",
  "Djanet",
  "Djelfa",
  "El Abiodh Sidi Cheikh",
  "El Aricha",
  "El Bayadh",
  "El Kantara",
  "El M'ghair",
  "El Menia",
  "El Oued",
  "El Tarf",
  "Ghardaïa",
  "Guelma",
  "Illizi",
  "In Guezzam",
  "In Salah",
  "Jijel",
  "Khenchela",
  "Ksar Chellala",
  "Ksar El Boukhari",
  "Laghouat",
  "M'Sila",
  "Mascara",
  "Messaâd",
  "Médéa",
  "Mila",
  "Mostaganem",
  "Naâma",
  "Oran",
  "Ouargla",
  "Ouled Djellal",
  "Oum El Bouaghi",
  "Relizane",
  "Saïda",
  "Sétif",
  "Sidi Bel Abbès",
  "Skikda",
  "Souk Ahras",
  "Tamanrasset",
  "Tébessa",
  "Tiaret",
  "Timimoun",
  "Tindouf",
  "Tipaza",
  "Tissemsilt",
  "Tizi Ouzou",
  "Tlemcen",
  "Touggourt",
] as const;

export type Wilaya = (typeof WILAYAS)[number];
